version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: et3ch
      POSTGRES_DB: todolist
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: ./ 
    command: ["sh", "-c", "./wait-for-it.sh db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./todo-list-backend
    ports:
      - "8000:8000"
    depends_on:
      - db 
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
